### ISSUE TITLE
Can somebody explain to me how to user koa-multer with file stream?

### ISSUE THREAD

**Issue by djrolleyes** [koajs/multer#13]
Can somebody explain to me how to use koa-multer with file stream?
I would like to use filestream to know whether file size is above the limit or not and maybe to pipe it to the storage server.

**Comment by niftylettuce** [comment]
Read the README - you need to use `multer@2x` https://github.com/koajs/multer#install.  Then access the `.stream` property of the file per <https://github.com/expressjs/multer/tree/explore-new-api#file-information>.

If multiple files (e.g. first key): `console.log('ctx.files[0]', ctx.files[0].stream);`

If single files: `console.log('ctx.file', ctx.file.stream);`

**Comment by djrolleyes** [comment]
@niftylettuce there is an issue when I try to instarll multer@2.x should I just use npm i multer@2.x --save? or how to install it cause I got an error 

```npm ERR! notarget No matching version found for multer@2.x.```

**Comment by niftylettuce** [comment]
https://www.npmjs.com/package/multer/v/2.0.0-beta.1

**Comment by djrolleyes** [comment]
@niftylettuce tnx. looks like there is no diskStorage anymore... Is the any example how to use in now?

**Comment by niftylettuce** [comment]
Use `fs.createWriteStream` to write the stream to disk
