### ISSUE TITLE
Missing Files 

### ISSUE THREAD

**Issue by 3imed-jaberi** [koajs/multer#20]
I see that is missing some files, for example:
  - History.md || CHANGELOG.md
  - Authors.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md

@niftylettuce, what do you think 🤔?

**Comment by niftylettuce** [comment]
I stopped doing a History.md and CHANGELOG.md as I use `np` to manage releases and have them posted here <https://github.com/koajs/multer/releases>.

Authors.md is not necessary if we update "collaborators" in `package.json` and then use https://lass.js.org style remark setup.  See https://github.com/lassjs/lass/blob/master/package.json#L35-L39 and https://github.com/lassjs/lass/blob/master/package.json#L145-L149 and https://github.com/lassjs/lass/blob/master/package.json#L156 and https://github.com/lassjs/lass/blob/master/README.md#contributors (auto generated `## Contributors` section.

People don't read code of conducts or contributing anyways, at least what I've found from managing hundreds of packages, so I just ignore those.
